update teams set short_name = 'None' where id = 1;
update teams set short_name = 'Arsenal' where id = 2;
update teams set short_name = 'Aston Villa' where id = 3;
update teams set short_name = 'Blackburn' where id = 4;
update teams set short_name = 'Bolton' where id = 5;
update teams set short_name = 'Charlton' where id = 6;
update teams set short_name = 'Chelsea' where id = 7;
update teams set short_name = 'Derby' where id = 8;
update teams set short_name = 'Everton' where id = 9;
update teams set short_name = 'Fulham' where id = 10;
update teams set short_name = 'Ipswich' where id = 11;
update teams set short_name = 'Leeds' where id = 12;
update teams set short_name = 'Leicester' where id = 13;
update teams set short_name = 'Liverpool' where id = 14;
update teams set short_name = 'Man Utd' where id = 15;
update teams set short_name = 'Middlesbrough' where id = 16;
update teams set short_name = 'Newcastle' where id = 17;
update teams set short_name = 'Southampton' where id = 18;
update teams set short_name = 'Sunderland' where id = 19;
update teams set short_name = 'Tottenham' where id = 20;
update teams set short_name = 'West Ham' where id = 21;
update teams set short_name = 'Birmingham' where id = 22;
update teams set short_name = 'West Brom' where id = 23;
update teams set short_name = 'Man City' where id = 24;
update teams set short_name = 'Portsmouth' where id = 25;
update teams set short_name = 'Wolves' where id = 26;
update teams set short_name = 'Norwich' where id = 27;
update teams set short_name = 'Crystal Palace' where id = 28;
update teams set short_name = 'Deleted' where id = 29;
update teams set short_name = 'Wigan' where id = 30;
update teams set short_name = 'Sheffield Utd' where id = 31;
update teams set short_name = 'Reading' where id = 32;
update teams set short_name = 'Watford' where id = 33;
update teams set short_name = 'Hull' where id = 34;
update teams set short_name = 'Stoke' where id = 35;
update teams set short_name = 'Burnley' where id = 36;
update teams set short_name = 'Blackpool' where id = 37;
update teams set short_name = 'Queens Park' where id = 38;
update teams set short_name = 'Swansea' where id = 39;
update teams set short_name = 'Cardiff' where id = 40;
update teams set short_name = 'Bournemouth' where id = 41;
update teams set short_name = 'Huddersfield' where id = 42;
update teams set short_name = 'Brighton' where id = 43;