update d11_teams set short_name = 'None' where id = 1;
update d11_teams set short_name = 'Andersson' where id = 2;
update d11_teams set short_name = 'Bolin/Gunnars' where id = 3;
update d11_teams set short_name = 'Boman' where id = 4;
update d11_teams set short_name = 'Egenfelt/Bengts' where id = 5;
update d11_teams set short_name = 'Ekholm' where id = 6;
update d11_teams set short_name = 'Solax' where id = 7;
update d11_teams set short_name = 'Eriksson J' where id = 8;
update d11_teams set short_name = 'Eriksson M&D' where id = 9;
update d11_teams set short_name = 'Eriks/Fonsell' where id = 10;
update d11_teams set short_name = 'Gröndahl' where id = 11;
update d11_teams set short_name = 'Jakobsson' where id = 12;
update d11_teams set short_name = 'Lindroos' where id = 13;
update d11_teams set short_name = 'Mattsson' where id = 14;
update d11_teams set short_name = 'Nyman' where id = 15;
update d11_teams set short_name = 'Sirén' where id = 16;
update d11_teams set short_name = 'Smeds' where id = 17;
update d11_teams set short_name = 'Sundström' where id = 18;
update d11_teams set short_name = 'Wahlfors/Wiklund' where id = 19;
update d11_teams set short_name = 'Viktorssons' where id = 20;
update d11_teams set short_name = 'Witting' where id = 21;
update d11_teams set short_name = 'Carlsson/Engblom' where id = 22;
update d11_teams set short_name = 'Ekholm/Berndts' where id = 23;
update d11_teams set short_name = 'Qvarnström' where id = 24;
update d11_teams set short_name = 'Rosén/Ekstrand' where id = 25;
update d11_teams set short_name = 'Carls/Brändström' where id = 26;
update d11_teams set short_name = 'Hjalmarsson' where id = 27;
update d11_teams set short_name = 'Eriksson M' where id = 28;
update d11_teams set short_name = 'Grönholm' where id = 29;
update d11_teams set short_name = 'Lindholm' where id = 30;
update d11_teams set short_name = 'Engblom' where id = 31;
update d11_teams set short_name = 'Sandberg' where id = 32;
update d11_teams set short_name = 'Ehres' where id = 33;
update d11_teams set short_name = 'Östergård' where id = 34;
update d11_teams set short_name = 'Egenfelt' where id = 35;
update d11_teams set short_name = 'Smeds R' where id = 36;
update d11_teams set short_name = 'Wiklund' where id = 37;
update d11_teams set short_name = 'Örblom' where id = 38;
update d11_teams set short_name = 'Egenfelt/Eriks' where id = 39;
update d11_teams set short_name = 'Boijer' where id = 40;
update d11_teams set short_name = 'Möller' where id = 41;
update d11_teams set short_name = 'Eriksson D' where id = 42;
update d11_teams set short_name = 'Holmberg' where id = 43;
update d11_teams set short_name = 'Karlsson' where id = 44;
update d11_teams set short_name = 'Jakobsson J' where id = 45;
update d11_teams set short_name = 'Kvarnström' where id = 46;
update d11_teams set short_name = 'Eriks/Jans' where id = 47;
update d11_teams set short_name = 'Eriksson N' where id = 48;
update d11_teams set short_name = 'Egenfelt/Östergård' where id = 49;
update d11_teams set short_name = 'Wilhelms' where id = 50;